class loginlocators:

    home_signin_btn = "/html/body/header[1]/div/div/div/div/div[4]/div/ul/li[4]/a/span"
    usename_xpath = "/html/body/div/div/div[2]/div[2]/form/div[1]/input"
    password_xpath = "/html/body/div/div/div[2]/div[2]/form/div[2]/input"
    signin_email = "email"
    signin_password = "password"
    signin_btn = "/html/body/div/div/div[2]/div[2]/form/div[4]/button"
    start_button = "startOrder"
    another_time_button = "selectAnotherTime"
    time_close_btn = "/html/body/div[7]/div/div/div/div[3]/button[1]"
    error_ok_btn = "/html/body/div[10]/div/div[4]/div/button"
    error_ok1 = "/html/body/div[9]/div/div[4]/div/button"
    select_time = '//*[@id="date-time-wrapper"]/div[2]/input'
    save_time_btn = "/html/body/div[7]/div/div/div/div[3]/button[2]"

    signedin_label = "//*[@id='menu-item-5']/a/span"
    signedin_label2 = "/html/body/header[1]/div/div/div/div/div[4]/div/ul/li[4]/a"
    logout_link = "//*[@id='menu-item-5']/ul/li[4]/a/span"
    contact_us = "/html/body/header[1]/div/div/div/div/div[4]/div/ul/li[3]/a"

    signup_name = "name"
    signup_email = "email"
    signup_password = "password"
    signup_confirmPassword = "password_confirmation"
    signup_btn = "/html/body/div/div/div[2]/div[1]/span[2]/a"
    register_btn = "/html/body/div/div/div[2]/div[2]/form/div[5]/button"
    error_msg = "/html/body/div/div/div[2]/div[2]/div/ul/li"
    forget_password_btn = "/html/body/div/div/div[2]/div[2]/form/div[3]/span[2]/a"
    forget_password_email_field = "//*[@id='email']"
    reset_link_btn = "/html/body/div/div/div[2]/form/div[2]/button"
    success_msg = "/html/body/div/div/div[2]/div[2]"
    error_msg1 = "/html/body/div/div/div[2]/div[2]/ul/li"

    profile_btn = "/html/body/header[1]/div/div/div/div/div[4]/div/ul/li[4]/ul/li[1]/a/span"
    name_in_profile = "/html/body/div[10]/div/div/div[2]/div/div[3]/h3"
    email_in_profile = "/html/body/div[10]/div/div/div[2]/div/div[4]/p/b"
    phone_in_profile = "/html/body/div[10]/div/div/div[2]/div/div[5]/p/b"
    edit_profile_btn = "/html/body/div[10]/div/div/div[2]/div/div[1]/a"
    name_edit = "/html/body/div[11]/div/div/div[2]/form/div[1]/input"
    update_profile_btn = "/html/body/div[11]/div/div/div[4]/button[2]"
    del_add_link = "//*[@id='menu-item-5']/ul/li[1]/a/span"
    add_new_address_btn = "/html/body/main/div/div[2]/div/div[1]/button"
    new_add_field = "searchbar"
    address_list = "/html/body/main/div/div[3]/div/div/div[1]/div/div[2]/div/div[1]/div/form/ul/li"
    add_hno = "house_name"

    address_add_message = "/html/body/main/div/div[3]/div/div/form/div/div[2]/div/div[2]/strong"
    save_add_btn = "/html/body/main/div/div[3]/div/div/form/div/div[3]/button[2]"
    update_add_btn = "/html/body/main/div/div[3]/div/div/div[2]/button[2]"
    warning_msg = "/html/body/div[8]/div/div[2]"
    ok_btn = "/html/body/div[8]/div/div[3]/div/button"
    close_btn = "/html/body/main/div/div[3]/div/div/div[2]/button[1]"
    address_table = "/html/body/main/div/div[2]/div/div[2]/div"
    asap_btn = "/html/body/main/div[1]/div/div[3]/div/div/div[2]/div[2]/ul/li[1]/a"
    now_btn = "/html/body/main/div[1]/div/div[3]/div/div/div[2]/div[3]/button[2]"
    later_btn = "/html/body/main/div[1]/div/div[3]/div/div/div[2]/div[2]/ul/li[3]/a"
    later_time = "/html/body/main/div[1]/div/div[3]/div/div/div[2]/div[2]/div[2]/div[3]/select"
    later_del_btn = "/html/body/main/div/div/div[4]/div/div/div/div/div[2]/div[3]/button[1]"

    home_page_heading = "//div[@id='home']/div/div/div/div/div/div/div/h2"

    aboutus_heading = "/html/body/main/div[2]/div/div[2]/div[1]/h5"
    openhours_heading = "/html/body/main/div[2]/div/div[2]/div[2]/div[2]/div/h5"
    opendays = "/html/body/main/div[2]/div/div[2]/div[2]/div[2]/div/div/div[1]/div[1]"
    openhours = "/html/body/main/div[2]/div/div[2]/div[2]/div[2]/div/div/div[1]/div[2]/div/span"
    close_days = "/html/body/main/div[2]/div/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/div[1]"
    close_text = "/html/body/main/div[2]/div/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/div[2]/div/span"
    partialday = "/html/body/main/div[2]/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div/div[1]"
    partial_time = "/html/body/main/div[2]/div/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div/div[2]/div/span"
    arrow = "/html/body/button"
    top_heading = "/html/body/main/div[1]/div/div[1]/div/div/div/h3"


class productlocators:
    products_list = "/html/body/main/div[2]/div/div[1]/div[2]/div[2]/div[2]/div[2]/div/div"
    menugroup_list = '/html/body/main/div[2]/div/div[1]/div[1]/ul'
    special_inst = "/html/body/div[8]/div/div/div/div/div/div[3]/div[1]/div[5]/div/textarea"
    quantity = "/html/body/div[8]/div/div/div/div/div/div[3]/div[2]/div[1]/form/input[1]"
    product_price = "/html/body/div[7]/div/div/div/div/div/div[3]/div[1]/div[1]/div/h6/span"
    add_to_bag = "/html/body/div[7]/div/div/div/div/div/div[2]/div[4]/div[2]/button"
    add_to_bag_btn2 = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[2]/button"
    cart_btn = "/html/body/header[1]/div/div/div/div/div[4]/div/ul/li[5]/span/span[2]"
    size = "/html/body/div[6]/div/div/div/div/div/div[3]/div[1]/div[2]/div[2]/div/div/label/span"
    crust = "/html/body/div[6]/div/div/div/div/div/div[3]/div[1]/div[3]/div/div[2]/div[1]/div/label/span"
    cart_xpath = "/html/body/main/div/div/div[6]/div[2]/div[2]/div[3]/div/div/div[1]/div"
    cart2 = "/html/body/header[1]/div/div/div/div/div[2]/div/ul/li[5]/span"
    cart_table = "/html/body/main/section/div[1]"
    crx_cart = "/html/body/main/section/header/i"

    topping1 = "/html/body/div[6]/div/div/div/div/div/div[3]/div[1]/div[2]/div[2]/div[1]/div/label"
    topping2 = "/html/body/div[6]/div/div/div/div/div/div[3]/div[1]/div[2]/div[2]/div[6]/div"
    dressing = "/html/body/div[6]/div/div/div/div/div/div[3]/div[1]/div[2]/div[2]/div[1]/div"

    extra_topping = "/html/body/div[6]/div/div/div/div/div/div[3]/div[1]/div[3]/div[2]/div[1]/div"
    change_link_xpath = "/html/body/main/div[1]/div/div[3]/div/div/div[1]/div[2]/div[2]/div[2]/div/div/a"
    change_date_time_path = "/html/body/main/div[1]/div/div[3]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div[1]/div[2]/p/a"
    order_type_link = "/html/body/header[1]/div/div/div/div/div[2]/ul/li/a"
    del_link_path = "/html/body/main/div[1]/div/div[3]/div/div/div/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/a"
    del_link_path2 = "/html/body/div[5]/div/div/div/div/div[1]/div[2]/div[2]/div[1]/div[1]/div/a"
    pickup_link_path = "/html/body/main/div[1]/div/div[2]/div[2]/div[2]/ul/li[2]/a"
    pickup_link_path2 = "/html/body/main/div[1]/div/div[3]/div/div/div/div[2]/div/div/div[1]/div/div[1]/ul/li[2]/a"
    del_date_time = "/html/body/main/div/div/div[4]/div/div/div/div/div[1]/div[2]/div[2]/div[1]/div[1]/div/a"
    del_date_time2 = "/html/body/main/div/div[1]/div[2]/div/div/div/div/div[1]/div[2]/div[2]/div[1]/div[1]/div/a"
    date_time_xpath = "/html/body/main/div/div/div[4]/div/div/div/div/div[1]/div[2]/div[2]/div[2]/div/div/a"
    time_path = "/html/body/main/div[1]/div/div[3]/div/div/div/div[2]/div/div/div[2]/div/div/div[3]/div[2]/input"
    select_time2 = "/html/body/div[7]/div/ul/li[3]/a"
    select_time = "/html/body/div[7]/div/ul/li"
    time_scroll = "/html/body/main/div[1]/div/div[3]/div/div/div[2]/div[2]/div[2]/div[2]/select"
    time_scroll2 = "/html/body/main/div/div[1]/div[2]/div/div/div/div/div[2]/div[2]/div[2]/div[2]/select"
    del_pipckup_btn2 = "/html/body/main/div[1]/div/div[3]/div/div/div/div[3]/button[3]"
    final_btn = "/html/body/main/div[1]/div/div[3]/div/div/div[2]/div[3]/button[1]"
    final_btn2 = "/html/body/main/div/div[1]/div[2]/div/div/div/div/div[2]/div[3]/button"
    address_field = "/html/body/main/div[1]/div/div[3]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div[2]/div[1]/input"
    address_field2 = "/html/body/main/div/div[1]/div[2]/div/div/div/div/div[1]/div[2]/div[2]/div[1]/div[2]/div/input[7]"
    add_field = "/html/body/div[5]/div/div/div/div/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/select"
    update_btn = "/html/body/main/div[1]/div/div[3]/div/div/div/div[3]/button[2]"
    update_btn2 = "/html/body/div[5]/div/div/div/div/div[1]/div[3]/button"
    invalid_address_err = "/html/body/div[2]/p"
    order_label = "/html/body/main/div[1]/div/div[2]/div[2]/div[1]/span"

    delivery_address_list = "/html/body/main/div[1]/div/div[3]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div[2]/ul"

    deleted_item = "/html/body/main/section/div[1]/div/div[1]/div/div[1]/div[1]/div/div/div[1]/div/button[1]"
    yes_btn = "/html/body/main/section/div[1]/div/div[1]/div/div[2]/aside/div/div/button[1]"
    empty_bag = "/html/body/main/section/div[2]/div[2]/div/button"
    empty_bag2 = "/html/body/main/div[1]/section/div[2]/div[2]/div/button"
    empty_bag_heading = "/html/body/main/section/header/strong/span"
    empty_cart_yes = "/html/body/main/section/div[1]/div/div[1]/div/div[3]/aside/div/div/button[1]"
    empty_cart_yes2 = "/html/body/main/div[1]/section/div[1]/div/div[1]/div/div[3]/aside/div/div/button[1]"
    cart = "/html/body/main/div/div/div[6]/div[2]/div[2]/div[3]/div/div/div[1]/div/div[2]"
    checkout_btn = "/html/body/main/section/div[2]/div[2]/a"
    product_instruction = "instruction"
    product_instructions = "instruction-2"
    product_instructions3 = "instruction-3"

    product_name = "/html/body/main/div[2]/div/div[1]/div[2]/div[2]/div[3]/div[2]/div/div[1]/div[1]/div/div/div/div/h6/a"
    product_cart_heading = "/html/body/div[5]/div/div/div/div/div/div[3]/div[1]/div[1]/div/h5"

    pizza_size = "/html/body/div[5]/div/div/div/div/div/div[3]/div[1]/div[2]"
    pizza_small_size = "//*[@id='menuselect']/div/div/div/div/div/div[2]/div[3]/div[1]/div[2]/div[1]/div/label/div"
    pizza_large_size = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[1]/div[2]/div[2]/div"
    pizza_Xlarge_size = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[1]/div[2]/div[3]/div"
    cheese_path = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[1]/div[1]/div[2]/div[2]/div/label/div[1]/span[1]"
    wing_size = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[1]/div[2]/div[1]/div"
    BBQ_sauce = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[2]/div[1]/div[2]/div[3]/div/label/div[1]/span[1]"

    ceaser_dressing = "/html/body/div[7]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div[1]/div/label/div[1]/span[1]"
    vinegar_dressing = "/html/body/div[7]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div[9]/div/label/div[1]/span[1]"
    italian_dressing = "/html/body/div[7]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div[4]/div/label/div[1]/span[1]"

    extra_wrap = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[1]/div[1]/div[2]/div[2]/div/div/div[1]/span[1]"
    sides_wrap = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[1]/div[2]/div[2]/div[1]/div/label/div[1]/span[1]"
    salt_topping = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[1]/div[3]/div[2]/div[1]/div/div/div[1]/span[1]"

    white_bread = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[1]/div[1]/div[2]/div[2]/div/label/div[1]/span[1]"

    cans_beverages = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[1]/div/div[2]/div/div/label/div[1]/span[1]"

    onion_topping = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[3]/div/div[2]/div[3]/div/label/div[1]/span[1]"
    spinach_topping = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[3]/div/div[2]/div[1]/div/label/div[1]/span[1]"
    mushroom_topping = "/html/body/div[8]/div/div/div/div/div/div[2]/div[3]/div[3]/div/div[2]/div[15]/div/label/div[1]/span[1]"
    pickels_extras = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[1]/div[2]/div[2]/div[4]/div/div/div[1]/span[1]"
    ketchup_extras = "/html/body/div[7]/div/div/div/div/div/div[2]/div[3]/div[1]/div[2]/div[2]/div[1]/div/div/div[1]/span[1]"
    pizza_crust_regulr = "/html/body/div[5]/div/div/div/div/div/div[3]/div[1]/div[3]/div/div[2]/div[1]/div/label/span"
    pizza_crust_thin = "/html/body/div[5]/div/div/div/div/div/div[3]/div[1]/div[3]/div/div[2]/div[2]/div/label/span"
    add_to_bag_btn = "//button[@onclick='foodAddToCart()']"
    special_insttructions = "/html/body/div[5]/div/div/div/div/div/div[3]/div[1]/div[5]/div/textarea"

    add_to_bag_btn_price = "btn_update_price1"
    edit_tobag_btn_price = "/html/body/div[5]/div/div/div/div/div/div[3]/div[2]/div[2]/button/span"
    edit_update_btn = "//button[@id='btn_update_pizza_price']"

    # additional toppings
    additionalToppng = "/html/body/div[5]/div/div/div/div/div/div[3]/div[1]/div[4]/div/div[1]/p"
    extra_cheese = "/html/body/div[5]/div/div/div/div/div/div[3]/div[1]/div[4]/div/div[2]/div[1]/div/label/span"
    turkey_ham = "/html/body/div[5]/div/div/div/div/div/div[3]/div[1]/div[4]/div/div[2]/div[2]/div/label/span"
    brocoli = "/html/body/div[5]/div/div/div/div/div/div[3]/div[1]/div[4]/div/div[2]/div[5]/div/label/span"
    green_peppr = "/html/body/div[5]/div/div/div/div/div/div[3]/div[1]/div[4]/div/div[2]/div[6]/div/label/span"


class cartLocators:
    cart_bag = "/html/body/header[1]/div/div/div/div/div[4]/div/ul/li[5]/span/span/i"
    product_price = "/html/body/main/section/div[1]/div/div/div/div[1]/div/div/div/div[2]/p"
    cart_subtotal = "/html/body/main/section/div[2]/div[1]/div[1]/div[2]"
    delivery_fee = "/html/body/main/section/div[2]/div[1]/div[2]/div[2]"
    estimated_tax = "/html/body/main/section/div[2]/div[1]/div[3]/div[2]"
    total = "/html/body/main/section/div[2]/div[1]/div[5]/div[2]/strong"
    checkout_price = "/html/body/main/section/div[2]/div[2]/a/p"
    checkout_btn = "/html/body/main/section/div[2]/div[2]/a"
    edit_btn = "/html/body/main/section/div[1]/div/div/div/div[1]/div/div/div/div[1]/div/button[2]"
    increase_qty = "increase"
    delete_item = "/html/body/main/section/div[1]/div/div/div/div[1]/div/div/div/div[1]/div/button[1]/i"
    remove_btn = "/html/body/main/section/div[1]/div/div/div/div[2]/aside/div/div/button[1]"
    empty_cart_headng = "/html/body/main/section/div[1]/div/div/div/div/h4"
    item_number = "/html/body/main/section/header/strong/span"
    cart_items = "/html/body/main/section/div[1]/div/div/div/div[1]"
    cart_increment_btn = "/html/body/main/section/div[1]/div/div/div/div[1]/div/div/div/form/div/button[2]"
    cart_decrement_btn = "/html/body/main/section/div[1]/div/div/div/div[1]/div/div/div/form/div/button[1]"

    cart_product1_qty = "//div[@class='quantity border']/input"


class checkoutlocators:
    edit_btn = "/html/body/main/div[1]/div[1]/div[1]/form/button"
    delivery_instructions = "/html/body/main/div[1]/div[1]/div/div[3]/div[2]/a"
    inst_textarea = "/html/body/main/div[1]/div[1]/div/div[3]/div[2]/textarea"
    contact_name = "/html/body/main/div[1]/div/div/div[2]/div[1]/p[1]/strong"
    date_time = "/html/body/main/div[1]/div/div/div[3]/div[1]/p/strong"
    contact_name2 = "/html/body/main/div[1]/div/div/div[3]/div[1]/p/span"
    date_time2 = "/html/body/main/div[1]/div[1]/div/div[3]/div[1]/p/strong"
    order_setting_heading = "/html/body/main/div[1]/div[1]/div[1]/div[1]/h6"
    cust_detail = "/html/body/main/div[1]/div[1]/div[1]/div[2]"
    change_settings = "/html/body/main/div[1]/div[1]/div[1]/div[2]/button"
    change_setting = "/html/body/main/div[1]/div/div/div[3]/div[3]/p/strong"
    contact_phone = "/html/body/main/div[1]/div[1]/div/div/form/div/div/div[3]/input"
    custome_tip_btn = "/html/body/main/div[1]/div[1]/div[3]/div[2]/div/div[5]/label/div"
    tip_xpath = "/html/body/main/div[1]/div[1]/div[3]/div[2]/div/div[5]/label/input"
    percent_tip = "/html/body/main/div[1]/div[1]/div[3]/div[2]/div/div[3]/label"
    contact_address = "/html/body/main/div[1]/div[1]/div/div/form/div/div/div[8]/div[1]/input"
    invalid_add_err_msg = "/html/body/div[3]/p"
    change_card_btn = "/html/body/main/div[1]/div[1]/div[2]/div[2]/a"
    add_new_card = "/html/body/main/div/div[1]/div[3]/form/div/div/div/div/div[3]/div[2]/div/input[1]"
    delete_card = "/html/body/main/div/div[1]/div[3]/form/div[1]/div[3]/div[2]/div/input[2]"
    select_card = "/html/body/main/div/div[1]/div[3]/form/div/div/div/div/div[3]/div[2]/div/select"
    contact_spec_ins = "/html/body/main/div[1]/div[1]/div/div/form/div/div/div[9]/textarea"
    secnd_deli_field = "/html/body/div[3]/div/div/div/div/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/select"
    review_heading = "/html/body/main/div/div[1]/div[1]/h2"
    heading6_on_payment = "/html/body/main/div[1]/div[1]/div/div[2]/div[1]/p[1]"
    card_name = "/html/body/main/div/div[1]/div[3]/form/div/div/div/div/div[3]/div[1]/div[1]/div[1]/div[1]/div/input"
    card_number = "/html/body/main/div/div[1]/div[3]/form/div/div/div/div/div[3]/div[1]/div[1]/div[1]/div[2]/div/input"
    month = "/html/body/main/div/div[1]/div[3]/form/div/div/div/div/div[3]/div[1]/div[1]/div[2]/div[2]/div/input"
    year = "/html/body/main/div/div[1]/div[3]/form/div/div/div/div/div[3]/div[1]/div[1]/div[2]/div[3]/div/input"
    remember_card = "/html/body/main/div/div[1]/div[3]/form/div/div/div/div/div[3]/div[1]/div[2]/span/input"
    cvc = "/html/body/main/div/div[1]/div[3]/form/div/div/div/div/div[3]/div[1]/div[1]/div[2]/div[1]/div/input"
    place_order_btn = "/html/body/main/div/div[1]/div[3]/form/div/div/div/button"
    Thank_heading = "/html/body/div[1]/div/h1"
    order_num_p = "/html/body/div[1]/div/p[1]"
    home_page_heading = "/html/body/section[1]/div[2]/div/div/div/div/div/div/div/h2"
    delivery_path = "/html/body/header[1]/div/div/div/div/div[2]/div[1]/ul/li/a[1]"
    pickup_path = "/html/body/header[1]/div/div/div/div/div[2]/div[1]/ul/li/a[2]"
    order_row = "/html/body/main/div/div/div[4]/div/table/tbody/tr[1]"
    order_id = "/html/body/div[2]/div[1]/div/div/ul/li[1]/b"
    product_name = "/html/body/div[2]/div[2]/table/tbody/tr/td[2]/tr[1]"
    order_type = "/html/body/main/div/div[1]/div[1]/div/h6[2]/span"
    name_in_order = "/html/body/main/div/div[1]/div[1]/div/p[1]"

    plus_add_address = "//*[@id='cardKnoxPaymentForm']/div/div[1]/div[1]/div/div[2]/div/div[1]/div[4]/div/div"
    plus_add_address2 = "/html/body/main/form/div/div[1]/div[1]/div/div[2]/div/div[1]/div[2]/div/div/i"
    new_address_bar = "new_add_field"
    address_sugg = "addressSuggestions"
    save_this_address_btn = "/html/body/div[6]/div/div/form/div/div[3]/button[2]"
    address_list = "/html/body/main/form/div/div[1]/div[1]/div/div[2]/div/div[1]"
    edit_add_btn = "/html/body/main/form/div/div[1]/div[1]/div/div[2]/div/div[1]/div[1]/div/div[2]/div[2]/a[2]"
    edit_hno_field = "house_name"
    remove_add_btn = "/html/body/main/form/div/div[1]/div[1]/div/div[2]/div/div[1]/div[1]/div/div[2]/div[2]/a[1]"
    remove_ok_btn = "/html/body/div[14]/div/div[4]/div[2]/button"

    plus_card_details = "/html/body/main/form/div/div[1]/div[2]/div[2]/div[1]/div/div[3]/div/div"
    plus_card_details2 = "/html/body/main/form/div/div[1]/div[2]/div[2]/div[1]/div/div[2]/div/div/i"
    card_owner_name = "/html/body/main/form/div/div[1]/div[2]/div[2]/div[2]/div/div/div/div[2]/div[1]/div[1]/input"
    new_card_number = "/html/body/main/form/div/div[1]/div[2]/div[2]/div[2]/div/div/div/div[2]/div[1]/div[2]/input[1]"
    new_expiry_month = "/html/body/main/form/div/div[1]/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/select"
    new_expiry_year = "expiry_year"
    new_cvc = "/html/body/main/form/div/div[1]/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div[3]/input"
    billing_address = "/html/body/main/form/div/div[1]/div[2]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/input[1]"
    save_card_btn = "/html/body/main/form/div/div[1]/div[2]/div[2]/div[2]/div/div/div/div[3]/button[2]"
    card_list = "/html/body/main/form/div/div[1]/div[2]/div[2]/div[1]/div"
    remove_card_btn = "/html/body/main/form/div/div[1]/div[2]/div[2]/div[1]/div/div[1]/div[1]/div/div[2]/a[2]"
    remove_card_ok = "/html/body/div[15]/div/div[4]/div[2]/button"
    ok_success_btn = "/html/body/div[15]/div/div[4]/div/button"


class menugroupLocators:
    combo = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[1]/a"
    pizza = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[2]/a"
    gourmet_Pizza = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[3]/a"
    strombolis = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[4]/a"
    burger = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[5]/a"
    chicken_over_rice = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[6]/a"
    desert = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[7]/a"
    side_orders = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[8]/a"
    wing_ding = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[9]/a"
    fried_chicken_platter = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[10]/a"
    chicken_nuggets = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[11]/a"
    chicken_fingers = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[12]/a"
    chicken_wings = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[13]/a"
    buffalo_wings = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[14]/a"
    salads = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[15]/a"
    pasta = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[16]/a"
    seafood_platter = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[17]/a"
    wraps = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[18]/a"
    hoagies = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[19]/a"
    gyro = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[20]/a"
    hot_cold_sandwiches = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[21]/a"
    club_sandwiches = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[22]/a"
    grilled_chicken = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[23]/a"
    chicken_steaks = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[24]/a"
    beef_steaks = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[25]/a"
    quesadilla = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[26]/a"
    beverages = "/html/body/main/div[2]/div/div[1]/div[1]/ul/li[27]/a"


class paymentLocators:
    cart_summary_hedng = "/html/body/main/form/div/div[2]/div/div[1]/h6"
    select_delivery_address = "/html/body/main/form/div/div[1]/div[1]/div/div[2]/div/div[1]/div[1]/div"
    payment_card = "/html/body/main/form/div/div[1]/div[2]/div[2]/div[1]/div/div[1]/div/div"
    palce_ur_ordr = "/html/body/main/form/div/div[2]/div/div[2]/a[1]"
    change_date_time = "/html/body/div[5]/div/div/div/div[2]/div/div/div[1]/div/div[2]/div[1]/div[2]/p/a"
    time_path = "/html/body/div[5]/div/div/div/div[2]/div/div/div[2]/div/div/div[3]/div[2]/input"
    select_time2 = "/html/body/div[8]/div/ul/li[4]/a"
    del_pipckup_btn2 = "/html/body/div[5]/div/div/div/div[3]/button[3]"
    update_btn = "/html/body/div[5]/div/div/div/div[3]/button[2]"


class placedPaymentLocators:
    heading = "/html/body/table/tbody/tr/td/div/table/tbody/tr[1]/td/table[1]/tbody/tr/td[1]"
    order_status = "/html/body/table/tbody/tr/td/div/table/tbody/tr[1]/td/table[1]/tbody/tr/td[2]"
    order_number = "/html/body/table/tbody/tr/td/div/table/tbody/tr[1]/td/table[2]/tbody/tr[1]/td[2]"
    subtotal = "/html/body/table/tbody/tr/td/div/table/tbody/tr[1]/td/table[2]/tbody/tr[7]/td[2]/table/tbody/tr[1]/td[2]"
    tax = "/html/body/table/tbody/tr/td/div/table/tbody/tr[1]/td/table[2]/tbody/tr[7]/td[2]/table/tbody/tr[2]/td[2]"
    discount = "/html/body/table/tbody/tr/td/div/table/tbody/tr[1]/td/table[2]/tbody/tr[7]/td[2]/table/tbody/tr[3]/td[2]"
    total = "/html/body/table/tbody/tr/td/div/table/tbody/tr[1]/td/table[2]/tbody/tr[7]/td[2]/table/tbody/tr[4]/td[2]"
    currntly_closd_msg = "/html/body/div[1]/p"
